### ISSUE TITLE
Remove icon sizing in `Button` CSS

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#1542]
BREAKING CHANGE: Users must set the size of icons used inside `Button`

When using our `Button` we have an opinionated styling on how big the icon should be, this is causing some problems in some use-cases.

```css
.button > :is(svg, img, i) {
  display: inline-block;
  height: var(--fc-button-icon-size);
  width: var(--fc-button-icon-size);
}

.small {
  --fc-button-icon-size: var(--fds-sizing-4);
}

.medium {
  --fc-button-icon-size: var(--fds-sizing-6);
}

.large {
  --fc-button-icon-size: var(--fds-sizing-8);
}
```

We have experienced;
- Some of the Aksel icons vary in size which means that sometimes you want to have bigger icons
- Some use-cases when using tertiary `Button` you would want bigger icons

Drawnback:
- People will always need to set the size on Aksel icons in `Button` in accordance with the choosen `size`
- People might pick the "wrong" icon size
```[tasklist]
### Tasks
- [ ] Remove CSS
- [ ] Add text to storybook about icon sizing
```
