### ISSUE TITLE
CSS modules compose and `:where` selector

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#3045]
When using `:where` selector are they composed when using css-modules [composes](https://github.com/css-modules/css-modules/blob/master/docs/composition.md)? 

For example;
```css
.my-input {
  composes: ds-input;
}
```

Will this compose this from `ds-input`?

```css
:where(.ds-input) {
  margin: 0; /* Reset native margin, but resepect parent selevtor `.someting > * { margin: ... }` */
}

.ds-input {
…
}
```
